### ISSUE TITLE
Implementation Paper

### ISSUE THREAD

**Issue by sabaronett** [sabaronett/demo-lab#1]
- [x] Pull latest from dtamayo/reboundx master
- [x] Tides + Interpolate test c85cff7b23321f4e6903ef1a53b2a612f831f99d
   - [x] Calculate tau from necessary parameters (Eq. 4)
   - [x] 4 Myr, Sun/Earth
   - [x] Try with Schroder shift
   - [x] Handle collisions
   - [x] Compare w/ & w/o tides (_R_<sub>&odot;</sub> upshift)
   - [x] IAS15 https://github.com/sabaronett/demo-lab/issues/1#issuecomment-634830384
   - [x] Extrapolate times (find rates) https://github.com/sabaronett/demo-lab/issues/1#issuecomment-634830384
- [x] Terrestrial planets sim (5 Myr)
   - [x] Without tides [`TerrestrialPlanets.ipynb`](https://github.com/sabaronett/demo-lab/blob/master/reboundx/implementation/sims/jupyter/TerrestrialPlanets.ipynb)
   - [x] With tides [`TerrestrialTides.ipynb`](https://github.com/sabaronett/demo-lab/blob/master/reboundx/implementation/sims/jupyter/TerrestrialTides.ipynb) (see [note](https://github.com/sabaronett/demo-lab/issues/1#issuecomment-633391082))
   - [x] Measure performance https://github.com/sabaronett/demo-lab/issues/1#issuecomment-634830384
   - [x] Extrapolate times (find rates) https://github.com/sabaronett/demo-lab/issues/1#issuecomment-634830384
- [x] Add'l terrestrial
   - [x] 60 Myr PTRGB c0d662de3b3ffec8224553211f5ba6175e3d4e27
   - [x] 118 Myr PTRGB df20ac7eba7a08b54dad5c3cc5cc4d1cececf84b
- [ ] Solar System (8 planets)
   - [x] 5 Myr 8cb5add79ca1f72a01208e728c6d350232db0d73
   - [ ] 30 Myr PTRGB (est. 2 hr)
   - [ ] 118 Myr PTRGB (est. 8 hr)
- [ ] Hot Jupiter
   - [ ] Tidal only

**Comment by sabaronett** [comment]
## Note about N-body tidal drag
Currently, the `tctl_tau` parameter is calculated only with the nearest surviving planet. Although other bodies in the simulation are subject to the `tides_constant_time_lag` force, the force's magnitude is affected only by the closest surviving planet.

**Comment by sabaronett** [comment]
# Performance
## WHFAST
As Dan claimed, turning the tidal force on/off yields no statistical difference in computational time when using a fixed-timestep, symplectic integrator (e.g., WHFAST).
### Sun-Earth

#### 4 Myr 
- **WSL1**: ~ 1.2 min
- **WSL2**: ~ 19 s

### Terrestrial Planets
#### 5 Myr
- **WSL1**: ~ 5 min
- **WSL2**: ~ 129 s
- **Cherry-Creek**<sup>1</sup>: 107.64 &pm; 0.28 s
#### 100 Myr
- **WSL2**: ~ 5700 s (1 hr 35 min)
- **Cherry-Creek**<sup>1</sup>: 7894.65 &pm; 31.87 s (2 hr 11 min 34 s)
#### Others
- 60 Myr : ~ 130 min (2 hr 10 min) (WSL1)
- 118 Myr : ~ 283 min (4 hr 43 min) (WSL1)
### Solar System
- 5 Myr : ~ 9.3 min (WSL1)
- 30 Myr : ~ ?? min
- 118 Myr : ~ ?? min

## IAS15
As IAS15 is non-symplectic and utilizes an adaptive timestep, there is a difference in total sim time since the orbital period will be shorter for close encounters.
- 4 Myr Sun-Earth
   - No tides: : ~ 13.5 min
   - Tides on: ~ 22.3 min
- 5 Myr Terrestrial: TBD

<i><sup>1</sup> Cherry-Creek specifications: **cp** | 48 "penguin" cherry-creek 2 (Penguin Computing Relion Servers) nodes (2 Intel Xeon E5-2640v3 8 core, 128Gb ram)</i>
